packages:
  - "packages/*"
allowBuilds:
  esbuild: true
  nx: true
# “During installation, these packages are trusted and are allowed to execute their build/install scripts.”
onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
